### ISSUE TITLE
Should logo file be packaged with application to avoid external request?

### ISSUE THREAD

**Issue by bigon** [openzipkin/zipkin-classic#13]
Hello,

With zipkin 2.19.2, it seems that the top logo is missing (I get a 404 from https://zipkin.io/public/img/zipkin-logo-200x119.jpg)

Shouldn't the logo be bundled in the .jar file to avoid a call to an external website?

**Comment by adriancole** [comment]
yeah heh sorry we are spamming the wrong repo :P

**Comment by jeqo** [comment]
I've created a PR #12 to fix this.
