### ISSUE TITLE
Zipkin logo is missing on the Classic Zipkin UI

### ISSUE THREAD

**Issue by msmsimondean** [openzipkin/zipkin-classic#4]
Hi.  The Classic Zipkin UI is serving a 404 for the Zipkin logo.  The path it is pointing to is https://zipkin.io/public/img/zipkin-logo-200x119.jpg.  

See https://github.com/openzipkin/zipkin-classic/blob/master/templates/layout.mustache#L3

**Comment by shakuzen** [comment]
Resolved by #7
